#!/usr/bin/env bun
// Generates the extension's preview stylesheet and mermaid config from MDReader's own
// `--dump-css` output, so the VS Code preview and the app can never drift apart: the
// colors live once, in the app's theme JSON, and this script re-derives everything.
//
// Usage: bun scripts/build-theme-css.ts   (or: mise run vscode:css, from the repo root)
// Override the app used for the dump with MDREADER_BIN=/path/to/MDReader.

import { existsSync } from "node:fs";
import { basename, dirname, join } from "node:path";

const extensionRoot = dirname(import.meta.dir);
const repoRoot = dirname(extensionRoot);
const mediaDir = join(extensionRoot, "media");

/** VS Code sets one of these classes on the preview's body from the active color theme. */
const VARIANT_SCOPES = {
  dark: ["body.vscode-dark", "body.vscode-high-contrast"],
  light: ["body.vscode-light", "body.vscode-high-contrast-light"],
} as const;

type Variant = keyof typeof VARIANT_SCOPES;

// --- MDReader binary ------------------------------------------------------------

function candidateBinaries(): string[] {
  const candidates = [
    process.env.MDREADER_BIN,
    "/Applications/MDReader.app/Contents/MacOS/MDReader",
  ];
  // A local debug build, so the dump can be regenerated from uncommitted theme edits
  // before the app is reinstalled.
  const derived = Bun.spawnSync([
    "xcodebuild", "-scheme", "MDReader", "-configuration", "Debug", "-showBuildSettings",
  ], { cwd: repoRoot });
  const settings = derived.success ? derived.stdout.toString() : "";
  const productsDir = settings.match(/ BUILT_PRODUCTS_DIR = (.+)/)?.[1]?.trim();
  if (productsDir) {
    candidates.push(join(productsDir, "MDReader.app/Contents/MacOS/MDReader"));
  }
  return candidates.filter((path): path is string => Boolean(path));
}

/**
 * First candidate that exists AND understands `--dump-css`. A build predating the flag
 * ignores it and opens the GUI instead of printing and exiting, so each probe is capped
 * by a timeout and killed: an outdated app flashes a window for a second, then the next
 * candidate is tried.
 */
function resolveBinary(): string {
  const tried: string[] = [];
  for (const candidate of candidateBinaries()) {
    if (!existsSync(candidate)) continue;
    tried.push(candidate);
    const probe = Bun.spawnSync([candidate, "--dump-css", "vars", "dark"], {
      timeout: 5_000,
      killSignal: "SIGKILL",
    });
    if (probe.success && probe.stdout.toString().includes("--background:")) return candidate;
  }
  const detail = tried.length ? `tried: ${tried.join(", ")}` : "no MDReader.app found";
  throw new Error(`no MDReader build supporting --dump-css (${detail}); set MDREADER_BIN`);
}

function dump(binary: string, mode: string, variant?: Variant): string {
  const args = ["--dump-css", mode, ...(variant ? [variant] : [])];
  const result = Bun.spawnSync([binary, ...args]);
  if (!result.success) {
    throw new Error(`${basename(binary)} ${args.join(" ")} failed: ${result.stderr.toString().trim()}`);
  }
  return result.stdout.toString().trim();
}

// --- CSS composition -----------------------------------------------------------

/**
 * Prefixes every selector in a flat stylesheet with each scope, so variant-specific
 * colors (highlight.js, mermaid) only apply under the matching VS Code body class.
 * The input is always MDReader's own dumped color rules: flat `selectors { decls }`
 * blocks with no at-rules and no nesting.
 */
function scopeRules(css: string, scopes: readonly string[]): string {
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const blocks = withoutComments.matchAll(/([^{}]+)\{([^{}]*)\}/g);
  const scoped: string[] = [];
  for (const [, rawSelectors, declarations] of blocks) {
    const selectors = rawSelectors.split(",").map((s) => s.trim()).filter(Boolean);
    if (!selectors.length) continue;
    const combined = scopes.flatMap((scope) => selectors.map((sel) => `${scope} ${sel}`));
    scoped.push(`${combined.join(",\n")} {${declarations.trimEnd()} }`);
  }
  return scoped.join("\n");
}

function themeStylesheet(binary: string): string {
  const sections = [
    "/* Generated by scripts/build-theme-css.ts from MDReader --dump-css. Do not edit. */",
    "/* Shared element rules; every color resolves through the per-variant variables below. */",
    dump(binary, "rules"),
  ];
  for (const variant of Object.keys(VARIANT_SCOPES) as Variant[]) {
    const scopes = VARIANT_SCOPES[variant];
    sections.push(
      `/* --- ${variant} ------------------------------------------------------------ */`,
      `${scopes.join(",\n")} {\n${dump(binary, "vars", variant)}\n}`,
      scopeRules(dump(binary, "highlight", variant), scopes),
      scopeRules(dump(binary, "mermaid-rules", variant), scopes),
    );
  }
  return `${sections.join("\n\n")}\n`;
}

/**
 * Both variants' mermaid `initialize()` configs as a global, for the preview script to
 * pick from once it knows which body class VS Code applied.
 */
function mermaidConfigScript(binary: string): string {
  const configs = (Object.keys(VARIANT_SCOPES) as Variant[]).map(
    (variant) => `  ${variant}: ${dump(binary, "mermaid-config", variant)}`,
  );
  return [
    "// Generated by scripts/build-theme-css.ts from MDReader --dump-css. Do not edit.",
    "window.mdreaderMermaidConfig = {",
    configs.join(",\n"),
    "};",
    "",
  ].join("\n");
}

// --- main ----------------------------------------------------------------------

async function main(): Promise<void> {
  const binary = resolveBinary();
  await Bun.write(join(mediaDir, "mdreader-theme.css"), themeStylesheet(binary));
  await Bun.write(join(mediaDir, "mdreader-mermaid-config.js"), mermaidConfigScript(binary));
  // The preview loads the app's own mermaid runtime, so diagrams parse identically.
  const runtime = join(repoRoot, "Sources/MDReader/Resources/mermaid.min.js");
  await Bun.write(join(mediaDir, "mermaid.min.js"), Bun.file(runtime));
}

await main();
